# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.IntegerField()),
                ('total_lines', models.IntegerField()),
                ('rail', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Route'),
        ),
        migrations.AddField(
            model_name='line',
            name='station1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station1', to='map.Station'),
        ),
        migrations.AddField(
            model_name='line',
            name='station2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station2', to='map.Station'),
        ),
    ]
