# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20171222_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='stripe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='sid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
