# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20171223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='rail',
            field=models.IntegerField(),
        ),
    ]
